image:
  file: .gitpod.dockerfile
ports:
  - port: 3000
  - port: 3333
  - port: 19000-19002
  - port: 5037
  - port: 4040
tasks:
  - command: cd backend && yarn && npx knex migrate:latest && yarn start
  - command: cd frontend && yarn && yarn start
  - command: cd mobile && yarn && yarn start
